# Generated by Django 4.1 on 2022-08-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.PositiveBigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
