# Generated by Django 4.1 on 2022-08-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('emp_id', models.IntegerField()),
                ('emp_salary', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
