# Generated by Django 4.1 on 2022-08-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0005_alter_usermodel_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('semester', models.CharField(max_length=255)),
            ],
        ),
    ]
