# Generated by Django 4.1 on 2022-08-14 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='blog_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogers.blogmodel'),
        ),
    ]
